spring.application.name=kpstore
spring.data.mongodb.uri=mongodb://localhost:27017/kpstore
spring.data.mongodb.database=kpstore
server.port=8080
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}